# Use the official Python image as the base
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ../semantic-kernel-service/ .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 8082 available to the world outside this container
EXPOSE 8082

# Run semantic_kernel_service.py when the container launches
CMD ["python", "semantic_kernel_service.py"]