# Use the official Golang image as the base
FROM golang:1.21.1

# Set the working directory inside the container
WORKDIR /app

# Copy the Go app files to the working directory
COPY main.go go.mod go.sum ./

# Download dependencies
RUN go mod download

# Build the Go app
RUN go build -o main main.go

# Expose port 8080
EXPOSE 8080

# Command to run the executable
CMD ["./main"]